import {defineField, defineType} from 'sanity'

export const seo = defineType({
  name: 'seo',
  title: 'SEO',
  type: 'document',
  groups: [
    {name: 'global', title: 'Global', default: true},
    {name: 'pages', title: 'Core pages'},
    {name: 'templates', title: 'Templates'},
  ],
  fields: [
    defineField({
      name: 'siteUrl',
      title: 'Canonical site URL',
      description: 'Production domain used for canonical URLs, Open Graph URLs, and robots sitemap reference.',
      type: 'url',
      initialValue: 'https://www.demennis.be',
      group: 'global',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'defaultTitle',
      title: 'Default title',
      description: 'Fallback browser/search title when a page does not provide one.',
      type: 'string',
      initialValue: 'De Mennis',
      group: 'global',
      validation: (r) => r.required().max(70),
    }),
    defineField({
      name: 'titleTemplate',
      title: 'Title template',
      description: 'Use %s where the page title should appear, e.g. %s | De Mennis.',
      type: 'string',
      initialValue: '%s | De Mennis',
      group: 'global',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'defaultDescription',
      title: 'Default meta description',
      description: 'Fallback description for search and social previews.',
      type: 'text',
      rows: 3,
      initialValue: 'Cinematic video work, brand films, reels and creative direction by De Mennis.',
      group: 'global',
      validation: (r) => r.required().min(50).max(170),
    }),
    defineField({
      name: 'defaultSocialImage',
      title: 'Default social image URL',
      description: 'Absolute image URL used for Open Graph and Twitter previews when a page has no custom image.',
      type: 'url',
      group: 'global',
    }),
    defineField({
      name: 'defaultSocialImageAlt',
      title: 'Default social image alt text',
      type: 'string',
      group: 'global',
    }),
    defineField({
      name: 'twitterHandle',
      title: 'Twitter/X handle',
      description: 'Optional. Include @, e.g. @demennis.',
      type: 'string',
      group: 'global',
    }),
    defineField({
      name: 'homeH1',
      title: 'Homepage H1',
      description: 'Visually hidden heading used for SEO and accessibility on the homepage.',
      type: 'string',
      initialValue: 'De Mennis',
      group: 'pages',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'homeTitle',
      title: 'Homepage title',
      type: 'string',
      initialValue: 'De Mennis',
      group: 'pages',
      validation: (r) => r.required().max(70),
    }),
    defineField({
      name: 'homeDescription',
      title: 'Homepage meta description',
      type: 'text',
      rows: 3,
      group: 'pages',
      validation: (r) => r.max(170),
    }),
    defineField({
      name: 'homeSocialImage',
      title: 'Homepage social image URL',
      type: 'url',
      group: 'pages',
    }),
    defineField({
      name: 'homeNoindex',
      title: 'Hide homepage from search results',
      type: 'boolean',
      initialValue: false,
      group: 'pages',
    }),
    defineField({
      name: 'projectsH1',
      title: 'Projects H1',
      description: 'Visually hidden heading used for SEO and accessibility on the projects page.',
      type: 'string',
      initialValue: 'Projects',
      group: 'pages',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'projectsTitle',
      title: 'Projects page title',
      type: 'string',
      initialValue: 'Projects',
      group: 'pages',
      validation: (r) => r.required().max(70),
    }),
    defineField({
      name: 'projectsDescription',
      title: 'Projects page meta description',
      type: 'text',
      rows: 3,
      group: 'pages',
      validation: (r) => r.max(170),
    }),
    defineField({
      name: 'projectsSocialImage',
      title: 'Projects page social image URL',
      type: 'url',
      group: 'pages',
    }),
    defineField({
      name: 'projectsNoindex',
      title: 'Hide projects page from search results',
      type: 'boolean',
      initialValue: false,
      group: 'pages',
    }),
    defineField({
      name: 'aboutTitle',
      title: 'About page title',
      type: 'string',
      initialValue: 'About',
      group: 'pages',
      validation: (r) => r.required().max(70),
    }),
    defineField({
      name: 'aboutDescription',
      title: 'About page meta description',
      type: 'text',
      rows: 3,
      group: 'pages',
      validation: (r) => r.max(170),
    }),
    defineField({
      name: 'aboutSocialImage',
      title: 'About page social image URL',
      type: 'url',
      group: 'pages',
    }),
    defineField({
      name: 'aboutNoindex',
      title: 'Hide about page from search results',
      type: 'boolean',
      initialValue: false,
      group: 'pages',
    }),
    defineField({
      name: 'categoryTitleTemplate',
      title: 'Category title template',
      description: 'Available token: %category%.',
      type: 'string',
      initialValue: '%category% Projects',
      group: 'templates',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'categoryDescriptionTemplate',
      title: 'Category description template',
      description: 'Available token: %category%.',
      type: 'text',
      rows: 3,
      initialValue: 'Explore %category% video projects by De Mennis.',
      group: 'templates',
      validation: (r) => r.required().max(170),
    }),
    defineField({
      name: 'workTitleTemplate',
      title: 'Work title template',
      description: 'Available tokens: %title%, %client%, %category%, %year%.',
      type: 'string',
      initialValue: '%title%',
      group: 'templates',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'workDescriptionTemplate',
      title: 'Work description template',
      description: 'Available tokens: %title%, %client%, %category%, %year%.',
      type: 'text',
      rows: 3,
      initialValue: '%title% is a %category% video project for %client% by De Mennis.',
      group: 'templates',
      validation: (r) => r.required().max(170),
    }),
  ],
  preview: {
    prepare() {
      return {
        title: 'SEO',
      }
    },
  },
})
