name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    env:
      PUBLIC_SANITY_PROJECT_ID: 454gxa26
      PUBLIC_SANITY_DATASET: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run checks
        run: npm run check

  backend:
    name: Sanity Studio
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    env:
      SANITY_STUDIO_PROJECT_ID: 454gxa26
      SANITY_STUDIO_DATASET: production
      SANITY_STUDIO_SITE_URL: https://www.demennis.be
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run checks
        run: npm run check
